### ISSUE TITLE
Doesn't seem to recognise `!` and `@`

### ISSUE THREAD

**Issue by pjebs** [jonnygreenwald/Fountain.ts#9]
`!` can be used to symbolise a definite action.
`@` can be used to symbolise a definite character name for the dialogue.

It seems to group `@` as Action instead.
Maybe the original library was made before the `!` and `@` were added to the specs.

**Comment by pjebs** [comment]
```
INT. BOOKSHOP - DAY

!William enters -- and there stands Anna -- in a simple blue skirt and top.

@ANNA
Hi.

@WILLIAM
Hello.

@ANNA
You disappeared.

@WILLIAM
Yeah -- Yeah -- I had to leave... I didn't want to disturb.
```

**Comment by pjebs** [comment]
```
0: {type: 'scene_heading', text: 'INT. BOOKSHOP - DAY', scene_number: undefined}
1: {type: 'action', text: '!William enters -- and there stands Anna -- in a simple blue skirt and top.'}
2: {type: 'action', text: '@ANNA<br />Hi.'}
3: {type: 'action', text: '@WILLIAM<br />Hello.'}
4: {type: 'action', text: '@ANNA<br />You disappeared.'}
5: {type: 'action', text: "@WILLIAM<br />Yeah -- Yeah -- I had to leave... I didn't want to disturb."}
```

**Comment by pjebs** [comment]
From https://www.fountain.io/syntax:

```
1.1 - March 14, 2014
New in Fountain 1.1:
A Character element can by forced by preceding it by an "at" symbol @.
An Action element can by forced by preceding it by an exclamation point !.
Lyrics are designated by a preceding tilde ~ on each line.
Deprecated in Fountain 1.1:
"Character Extensions"--the parenthetical notations that follow a character name on the same line--are no longer required to be uppercase.
Two trailing spaces no longer forces an Action line.
1.0 - February 7, 2012
Merged SPMD and Fountain specs into one.
```

The new regexes are in here:
https://github.com/nyousefi/Fountain/blob/master/Fountain/FountainRegexes.m

**Comment by jonnygreenwald** [comment]
> Maybe the original library was made before the ! and @ were added to the specs.

Yeah, pretty certain that is correct. Matt's and mine both only support _most_ of the syntax and I am pretty sure `v1.1` of Fountain is currently unsupported.

I have busy next couple of days but have started looking into supporting `v1.1` of the spec. Thanks for the links and documentation!

**Comment by jonnygreenwald** [comment]
Morning, hope this finds you well. 

Commits 1d2bd2a6fc379a32a6b17512638fcd57825deeec and 9a90be99a1236013719ebd91b6496a0d6ac72ed5 should bring Fountain.ts up to spec with Fountain `v 1.1` and with that I've released [Fountain.ts](https://www.npmjs.com/package/fountain.ts) finally as `v 1.0.0` on npm.

**Added**
- [x] A Character element can by forced by preceding it by an "at" symbol `@`.
- [x] An Action element can by forced by preceding it by an exclamation point `!`.
- [x] Lyrics are designated by a preceding tilde `~` on each line.

**Changed**
- [x] "Character Extensions"--the parenthetical notations that follow a character name on the same line--are no longer required to be uppercase.

As far as I know, this supports full Fountain spec, so given:

```none
INT. BOOKSHOP - DAY

!William enters -- and there stands Anna -- in a simple blue skirt and top.

@ANNA
Hi.

@WILLIAM
Hello.

@ANNA
You disappeared.

@WILLIAM
Yeah -- Yeah -- I had to leave... I didn't want to disturb.
```

You should now receive:

```Javascript
[
  { type: 'scene_heading', text: 'INT. BOOKSHOP - DAY', scene_number: undefined },
  { type: 'action', text: 'William enters -- and there stands Anna -- in a simple blue skirt and top.' },
  { type: 'dialogue_begin', dual: undefined, text: undefined },
  { type: 'character', text: 'ANNA' },
  { type: 'dialogue', text: 'Hi.' },
  { type: 'dialogue_end', text: undefined },
  { type: 'dialogue_begin', dual: undefined, text: undefined },
  { type: 'character', text: 'WILLIAM' },
  { type: 'dialogue', text: 'Hello.' },
  { type: 'dialogue_end', text: undefined },
  { type: 'dialogue_begin', dual: undefined, text: undefined },
  { type: 'character', text: 'ANNA' },
  { type: 'dialogue', text: 'You disappeared.' },
  { type: 'dialogue_end', text: undefined },
  { type: 'dialogue_begin', dual: undefined, text: undefined },
  { type: 'character', text: 'WILLIAM' },
  { type: 'dialogue', text: "Yeah -- Yeah -- I had to leave... I didn't want to disturb." },
  { type: 'dialogue_end', text: undefined }
]
```

Closing this for now but please feel free to post more issues if you need.

**Comment by pjebs** [comment]
Awesome work. Had it been registered with non?

**Comment by jonnygreenwald** [comment]
Yup! `V 1.0.1` is up on https://www.npmjs.com/package/fountain.ts.

Regards,

Jonny Greenwald
(310) 994-4805
http://jonnygreenwald.com

**Comment by pjebs** [comment]
Thank you for your awesome work. If you an acting student, you can use the app: https://petersir.com, which I built using your library.

**Comment by jonnygreenwald** [comment]
I quite appreciate the ability to rearrange and hide your partner's lines. While I've never been to acting school, I'd certainly like a tool like this. Great work.

**Comment by pjebs** [comment]
Normally you hide your **own** lines (so you can practice saying them).

**Comment by jonnygreenwald** [comment]
Ah, makes sense. It makes me happy to see more tools being made for filmmakers. Glad to contribute my small part to it ☺️

**Comment by pjebs** [comment]
What is your involvement with film making? What made you dabble in the fountain format?

**Comment by jonnygreenwald** [comment]
For most of my professional career, I've been in the film industry in one form or another mostly as an Editor, Cinematographer or VFX artist. Currently, I manage broadcast tech for a YouTube-based media company.

Throughout most of that, I've always enjoyed writing having written and directed several short films with a smattering of music videos here and there. I've always dabbled in Fountain, specifically when I didn't have any kind of official screenwriting software. I played around with several that had Fountain support like Celtx and Highland at the time but I eventually went to Final Draft. Knowing a lot of people who straight up just tab out dialogue in a text file, I've always kind of thought a markdown-like language may be of worthwhile. Fountain.ts was originally a way to learn Typescript thanks to my friend @rezonant who encouraged me to start maintaining a fork of Fountain.js.

**Comment by pjebs** [comment]
Interesting life story. Not the typical for a programmer!

**Comment by jonnygreenwald** [comment]
I can certainly see that. I guess I do at least have some relevant experience when it comes to screenwriting apps at least, lol. 

What was your inspiration for your app? What got you into writing a tool like this for actors?

**Comment by pjebs** [comment]
I am learning to act but struggling to memorise lines. I tried a few apps on the market and in my opinion they weren't _exactly_ what I was looking for. So I decided it was time to make it myself rather than wait.

**Comment by jonnygreenwald** [comment]
That's a great reason.  Memorizing lines can be a pain. I usually just focused on the context of my role's dialogue more than content, though some directors are bigger sticklers that. I frankly never bothered with fully learning the other person's lines. It helped me give a more genuine reaction even if I didn't fully know what they were going to say. Specifically when I wasn't worrying about what line came next. That being said, I never did a lot of formal acting training, so I'm no coach. 

Good luck with spreading the word! I hope you can get more to use this. I've always been excited about the potential for Fountain as an intermediary format to expand the process from screenplay to pre-production. This seems like a great example where someone could export their screenplay from say [Writer Duet](https://www.writerduet.com/) and give it to their actors via this for table reads, etc. 

Also, best of luck with the acting classes and hope your app helps you with memorization. If I get a chance, I'll let others know about it too and will let you know if I make any other upgrades to the library 👍
